# In: /your-server-projects/dbt/docker-compose.yml

version: '3.8'

services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.latest
    container_name: dbt_service
    restart: unless-stopped
    
    env_file:
      - .env
      
    # The volumes now require the DBT_PROJECT_PATH variable to be set
    volumes:
      - ${DBT_PROJECT_PATH:?ERROR: You must provide a path to a dbt project. See documentation.}
      - ${DBT_PROJECT_PATH:?}/profiles:/root/.dbt/
      
    working_dir: /usr/app/dbt
    
    command: ["rpc", "--host", "0.0.0.0", "--port", "8580"]
    
    ports:
      - "8580:8580"
      
    networks:
      - supabase_network

networks:
  supabase_network:
    name: supabase_default
    external: true