# In: /your-server-projects/dbt/docker-compose.yml

version: '3.8'

services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.latest
    container_name: dbt_service # The container will be named dbt-dbt_service-1, etc.
    
    env_file:
      - .env
      
    volumes:
      - ${DBT_PROJECT_PATH:?ERROR: You must provide a path to a dbt project.}
      - ${DBT_PROJECT_PATH:?}/profiles:/root/.dbt/
      
    working_dir: /usr/app/dbt
    
    # NO 'command' or 'ports' needed for `docker compose run`

networks:
  supabase_network:
    name: supabase_default
    external: true